name: LoxiLB-Rel-Docs 
on:
  release:
    types: [published]
    branches:
      - test
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
      - run: pip install --upgrade pip && pip install mkdocs mkdocs-gen-files mkdocs-mermaid2-plugin mkdocs-autorefs mkdocs-material mike jq
      - run: git config user.name 'github-actions[bot]' && git config user.email 'github-actions[bot]@users.noreply.github.com'
      - name: Get the latest version
        run: echo "version=$(curl --silent -m 10 --connect-timeout 5 "https://api.github.com/repos/loxilb-io/loxilb/releases/latest" | jq -r .name)" >> "$GITHUB_ENV"
      - name: Publish docs
        #run: mkdocs gh-deploy
        run: |
          mike delete ${{ env.version }}
          mike delete master
          mike deploy --push --update-aliases 0.9.6 latest
          mike set-default --push master
            
